### ISSUE TITLE
Upgrade Protobuf version

### ISSUE THREAD

**Issue by objmagic** [apache/incubator-heron#1183]
Protobuf team just [released version 3.0](https://github.com/google/protobuf/releases/tag/v3.0.0). Improvement of Python implementation looks promising.

**Comment by taishi8117** [comment]
Protobuf team states that it's not generally recommended to upgrade from proto2 to proto3, so if we do this, we would risk breaking the backward compatibility. 

If that's okay, it's also better to refactor other parts of protobuf to be more semantically generic (if necessary like #1181) at the same time as this upgrade.

**Comment by objmagic** [comment]
Let's be careful when upgrading to Protobuf 3.0 or making any change related to Protobuf. If someone makes change on Protobuf, I suggest he should at least:

1. Clean build the whole project
2. ``bazel test --config=darwin heron/...``
3. Run integration test under [integration-test](https://github.com/twitter/heron/tree/master/integration-test)
4. Submit a topology and manually verify `heron-explorer`, `heron-tracker`, and `heron-ui` work well
5. Pass internal CI (maybe this is optional)

**Comment by maosongfu** [comment]
Let's consider this upgrade together carefully, since we had a plan/thoughts tryting to replace protobuf with flat-buffer or something similar. If to replace, then this upgrade seems less meaningful.

**Comment by objmagic** [comment]
@kramasamy thinks for milestone 0.14.3, we should upgrade to Protobuf 3.0.0 and use C++ implementation underhood for Python protobuf. Investigating flatbuffer may take much longer time. cc @maosongfu

**Comment by maosongfu** [comment]
Let's discuss the priorities in hand in a meeting. Not sure how much workload is involved in this upgradation; also, to improve the protobuf-related performance issues for python instance seems not that critical for now, compared with others.

**Comment by objmagic** [comment]
cross-reference: #1217

**Comment by objmagic** [comment]
we are going to upgrade to 3.1.0

cf: https://github.com/twitter/heron/pull/1591

**Comment by Code0x58** [comment]
now using 3.8 so this can be closed https://github.com/apache/incubator-heron/pull/1591#issuecomment-613838466

**Comment by joshfischer1108** [comment]
thank you @Code0x58
