### ISSUE TITLE
Provide a logging bridge at runtime

### ISSUE THREAD

**Issue by ajorgensen** [apache/incubator-heron#1253]
This issue (https://github.com/twitter/heron/issues/620) triggered the removal of `log4j-over-slf4j` from the classpath which cause unintended consequences for topologies that have dependencies that use log4j directly. We should provide the logging bridges (`log4j-over-slf4j`, `slf4j-log4j12`, etc) at runtime on the classpath that can be configured and added independently depending on the need of the runtime.

**Comment by kramasamy** [comment]
thanks @ajorgensen - just wondering who would like to pick this up @ashvina, @ajorgensen, @nlu90

**Comment by ajorgensen** [comment]
I can do it or someone else is more than welcome to pick it up if they have time. I might have some time this weekend to work on it.
