### ISSUE TITLE
Kubernetes scheduler

### ISSUE THREAD

**Issue by prabhuinbarajan** [apache/incubator-heron#1452]
Kubernetes scheduler:
Support following operations:
Schedule a topology for launch
Restarting a topology for launch
Killing  a running topology
Detailed low level design for this will follow

Ref: https://docs.google.com/document/d/1pRhXp8LwPjUoY4jZBMmGcB_foqGuvsXmMlcgqjtfd10/edit

**Comment by caniszczyk** [comment]
I can't access that google doc cc: @kramasamy

**Comment by kramasamy** [comment]
@caniszczyk - permission granted. Anybody can comment on it? Can you point this to kubernetes contributors so that we can get some feedback?

**Comment by tnachen** [comment]
Part of the work we are doing for spark on k8s is a Java client that integrates with k8s, that I think Heron can use as well instead of shelling to kubectl.

**Comment by prabhuinbarajan** [comment]
@tnachen -  i agree. the kubectl reference was more an illustration for the reader on what should be accomplished. there were other options that were suggested. But reading the doc again, it seems that point isnt well communicated. i will reword it the design and stories...
I agree that if there is a native client library for kubernetes, that is what we should use. i will review the spark k8s client library -can you provide some reference to it so that i can lookup?

**Comment by Code0x58** [comment]
heron on kubernetes is available and in use by contributors, so I think this can be closed
