### ISSUE TITLE
Kubernetes Log Management

### ISSUE THREAD

**Issue by prabhuinbarajan** [apache/incubator-heron#1453]
Log management : aggregate the logs from the spouts and bolts and organize it by topology?
Ref: https://docs.google.com/document/d/1pRhXp8LwPjUoY4jZBMmGcB_foqGuvsXmMlcgqjtfd10/edit

**Comment by Code0x58** [comment]
I think this would only apply to the the topologies in the executors, which are written in their own language and user execution environment - generally this is probably best left to the users to find a balance between their language, cluster, log shipping, and application logging needs. Even going through every piece of code that write a log message and may be able to determine it's topology name, then putting that into the log message in a consistent format, might not yield much.

That would leave me tempted to close this as a non-issue/no great solution or requirement.

_p.s. in Kubernetes the general approach is to log to stdout and let leave aggregation to the cluster's log shipping. For me, the ideal is to have logs rendered into a JSON envelope (e.g. `{"level": "info", "message": "become the log", "tag": "value"}`). Then it can be nicely loaded into an ELK stack with a JSON filter (or similar elsewhere), then elements of data are very easy to explore and aggregate/filter._

**Comment by nicknezis** [comment]
I have some thoughts on how to do this for Loki in Kubernetes, but I agree with @Code0x58 . We will close this issue. We can make a new issue in the future if the topic comes up again.
