### ISSUE TITLE
heron cli: missing dependencies

### ISSUE THREAD

**Issue by objmagic** [apache/incubator-heron#1633]
Just put a note here:

Previous release of [heron client installation script](https://github.com/twitter/heron/releases/download/0.14.5/heron-client-install-0.14.5-darwin.sh) failed to work on machine with OS X version lower than 10.11, with the following error message:

````
Failed to execute PEX file, missing compatible dependencies for:
psutil
pyyaml
````

This is because the person (me) who created the installation script is using OS X of version 10.11. Some Python packages in PEX file, however, could only work on 10.11. Backward compatibility is lost.

@kramasamy, who is using OS X of version 10.10.x, replaced the bad installation script and uploaded a new one built on his machine, which should work on both 10.10.x and 10.11.

The issue here is that we should figure out a way to generate installation script on any machine (Docker configuration, some sort of VM? modify PEX configuration?). Otherwise, we can only rely on @kramasamy's machine (thus he can't upgrade his OS 🙃).

Related to https://github.com/twitter/heron/issues/831

**Comment by Code0x58** [comment]
The heron CLI works now, and is used in the integration tests
