### ISSUE TITLE
Move to bazel 0.4.x

### ISSUE THREAD

**Issue by kramasamy** [apache/incubator-heron#1769]

**Comment by objmagic** [comment]
minor comments:
1. We should upgrade to at least https://github.com/bazelbuild/bazel/releases/tag/0.4.3. The coverage report part looks helpful.

2. We probably need to special attention to make Bazel 0.4.x work in Twitter internal env.

**Comment by maosongfu** [comment]
Can we justify the reasons to move to bazel 0.4.x? There are already too many pending issues now and it is good if we can prioritize them.

**Comment by Code0x58** [comment]
now on Bazel 3.0.0
