### ISSUE TITLE
UI show status of the topology

### ISSUE THREAD

**Issue by kramasamy** [apache/incubator-heron#187]
Topology can be in one of the 2 following states
- running
- paused

It should be shown in the UI

**Comment by kramasamy** [comment]
@cckellogg - can you take a look at this issue?

**Comment by kramasamy** [comment]
@cckellogg - do you have an update on this?

**Comment by nwangtw** [comment]
there is a "status" column in heron UI now. can this ticket be resolved?

**Comment by nwangtw** [comment]
"state" is in UI, in the middle of the page.

Resolve for now. Feel free to create a new ticket with more specific requirements if the currently location is not desired.
