### ISSUE TITLE
Better error handling for K8S multi-pod submissions

### ISSUE THREAD

**Issue by jrcrawfo** [apache/incubator-heron#1981]
Referencing PR https://github.com/twitter/heron/pull/1970, we need to be able to better handle problems that may arise during a multi-pod submission. Since Kubernetes does not currently support submitting multiple pods for deployment in a single API call, a problem could arise where one of the containers fails to be added or destroyed and leave the topology in a bad state.

Possible solutions:
* Figure out a way to rollback existing submissions
* Use a different kind of deployment for K8S (possibly a Deployment object?). Would require changes where every container would have a common the same startup command -- which is impossible now since the container index is needed (which is different for every container)

**Comment by windhamwong** [comment]
This issue is 3 years ago, but i believe heron has more to do with this. To clarify one thing that, k8s supports multiple container within 1 pod, which means we can group up some into one to have cleaner setup.

**Comment by nicknezis** [comment]
Heron Kubernetes scheduler also now supports launching topologies using Kubernetes StatefulSets. I believe this issue has been satisfied with that functionality. There is still legacy code that launches the individual pods, but that most likely should be deprecated.

I'm closing the issue, but feel free to submit any new issues for features that are still lacking.
