### ISSUE TITLE
Remove binary packages from heron repo

### ISSUE THREAD

**Issue by billonahill** [apache/incubator-heron#2092]
Apache source releases must contain all source and supporting content to rebuild the distro locally, without binary artifacts. We must remove the binary artifacts and instead fetch them at build time. These are mostly cpp artifacts in the `3rdparty/` directory.

**Comment by billonahill** [comment]
One of the challenges with this is that Twitter's CI environment can't access the public internet. This can be done though by deploying a custom proxy rule. The challenge though is that the proxy must point to a valid URI path that's not a file. These files are examples of where we want to proxy:

https://github.com/google/protobuf/archive/v3.3.0.tar.gz
https://github.com/google/glog/archive/v0.3.5.tar.gz

But paths like `https://github.com/google/protobuf/archive/`are invalid and return 404s. @kramasamy do you know of another location where these can be pulled that actually mirrors a directory structure? Even path's like `https://github.com/google/protobuf/tree/v3.3.0` can be proxied, but the artifacts don't live below that path anywhere.

**Comment by billonahill** [comment]
@kramasamy we have the ability to upload artifacts to our internal repository and change WORKSPACE to point to them at build time. Could you submit a patch to migrate just one cpp library to use the http approach, maybe glog? We can then verify that patch internally before migrating the rest of them.

**Comment by kramasamy** [comment]
@billonahill - protobuf is already out.

**Comment by kramasamy** [comment]
This is addressed by the PR #2833 - let me know if anything else is remaining
