### ISSUE TITLE
Migrate code to Apache github

### ISSUE THREAD

**Issue by billonahill** [apache/incubator-heron#2133]
Once the SGA is submitted and the binaries are removed from `third_party/` we can plan the move of the codebase from twitter github to apache github.

Via slack (Matteo Merli in the apache-incubator room) this can be done by renaming github `twitter/heron` to apache/heron-incubator`, by filing an apache INFRA request and granting Heron github admin access to the infra person helping out.

> when setting up for Pulsar in incubator, last month, we have transferred the repo from yahoo/pulsar to apache/incubator-pulsar
and then asked INFRA to setup gitbox integration.
That makes the github repo to be the source of truth (all commits are merged on github and synced back into an ASF mirror)
also it controls the committers access through github account. Committers needs to link their github account with the apache id (on the gitbox setup page) and they’ll get write access to the github repo
(the nice part about transferring the repo, is that all the PRs issues are transferred as they are, with no disruptions. Also all the links to the old repo are still valid and will redirect to the new repo)

> You just need to give admin access to the twitter/heron to someone from ASF INFRA. At that point he will be able to change the organization for the repo. For reference, that’s the jira issue we have created for it: https://issues.apache.org/jira/browse/INFRA-14376

**Comment by billonahill** [comment]
Via [discussion](https://lists.apache.org/thread.html/a83095cd44e09fa179c4b5034e04acdb055a671406f1501a796700e0@%3Cdev.heron.apache.org%3E) on the apache mailing list, the code can be migrated to Apache gitbox without the SGA, and non-Apache releases can be still made a that point, so consensus was reached that we should move forward on this.

@maosongfu we will need to coordinate this move so Twitter's CI can change the location of the git repo. When would be best to do this?

**Comment by billonahill** [comment]
@maosongfu any comments on this? This is a blocker for the Apache migration.

**Comment by maosongfu** [comment]
@billonahill I have reported this to Twitter Lgeal and they are still working on it.

**Comment by billonahill** [comment]
Thanks @maosongfu. Just to clarify, this ticket is to move the code to apache git which can be done in parallel with legal working on the SGA. The latter doesn't block the former.

**Comment by billonahill** [comment]
@maosongfu any update on this? What's blocking the migration of the code from your end?

**Comment by maosongfu** [comment]
@billonahill  We checked with Twitter Legal and we are still waiting for their response.

**Comment by billonahill** [comment]
Done.
