### ISSUE TITLE
Provide a bookkeeper based uploader/downloader

### ISSUE THREAD

**Issue by sijie** [apache/incubator-heron#2219]
[Apache BookKeeper](http://bookkeeper.apache.org/) is a scalable, fault-tolerant, and low-latency storage service. It can be used for storing the topologies for heron. This change is to add bookkeeper based uploader/downloader.

**Comment by huijunwu** [comment]
is bookkeeper a candidate for heron/heron/statefulstorages/src/java/com/twitter/heron/statefulstorage/

**Comment by maosongfu** [comment]
@huijunw 
I think `statefulstorage` is for the backend to store checkpoints in stateful processing.
And uploader/downloader are for topology tarball storage.

**Comment by sijie** [comment]
@huijunwu 

As @maosongfu pointed out, this issue is for using bookkeeper for storing topology jars.

I have a pull request for use bookkeeper as the statefulstorage. it is coming out soon.

**Comment by Code0x58** [comment]
bookkeeper is now the default upload backend in kubernetes examples, so I think this is done
