### ISSUE TITLE
Looks like there is an error in heron/master/deploy/kubernetes/gcp/bookkeeper-apiserver.yaml

### ISSUE THREAD

**Issue by mjschmidt** [apache/incubator-heron#2584]
serviceaccount "heron-apiserver" created
clusterrolebinding "heron-apiserver" created
error: error converting YAML to JSON: yaml: line 7: did not find expected key

When i ran through the gpc kubernetes deployment I got this error

I took a look at the yaml and it looks like the spacing may be off?
https://raw.githubusercontent.com/twitter/heron/master/deploy/kubernetes/gcp/bookkeeper-apiserver.yaml

line 7 of the deployment. If that is the case I can make the fix and do a quick pull request.

**Comment by kramasamy** [comment]
@mjschmidt - Thanks for finding this. Please fix and send a pull request.

**Comment by mjschmidt** [comment]
Is this issue done then?

**Comment by kramasamy** [comment]
I think so.
