### ISSUE TITLE
Restore container's ability to run locally (or create new dev container with heron client in it so new heron container can stay small)

### ISSUE THREAD

**Issue by mjschmidt** [apache/incubator-heron#2667]
I attempted to spin up a heron/heron:latest docker container, bashing into the container (0.17.2) with

`docker exec -it container_name`

 and run a topology by issuing the heron command

`heron submit local /usr/local/heron/examples/heron-streamlet-examples.jar com.twitter.heron.examples.ExclamationTopology ExclamationTopology`

I get error when I try that? It is failing to find of load the main class from com.twitter.heron.examples.ExclamationTopology

**Comment by mjschmidt** [comment]
Also fails when I try to use the api jar. Goal is to easily spin up a dev environment where people can test heron locally quickly using docker without doing a build on their machine. This seems like a bug, I just tried it on the open internet as well.

**Comment by kramasamy** [comment]
@mjschmidt - streamlet examples do not contain ExclamationTopology. Instead try heron-api-examples.jar for ExclamationTopology

**Comment by kramasamy** [comment]
@mjschmidt - docker container is mainly to run in a cluster and currently it does not have heron client installed since the image size gets bigger. you can view the single docker container as a one node cluster and submit topology from the outside - let me see if I can improve the experience.

**Comment by mjschmidt** [comment]
@kramasamy 

0.17.2 (MAYBE .1 i forget)  does have the client installed  because I can run the heron command from inside the cluster and it works, java home is set etc. There is just something going on where it cannot access the Exclaimation Topology and I don't know enough about the container to know what that is. The new container you are right does not have the heron client in it, and ideally it would be super nice if the heron client worked in the debian container, but I was referring to the older container that was based off ubuntu.

Quick recap because I have found the way I say things can be confusing:
1) Heron client is in 17.2 (17.2) and works but I can't launch the topology locally by either bashing into the container or following the docker documentation found here:
https://github.com/twitter/heron/tree/master/docker
2) Yes I would love it if the new container (17.3) which is you guys' debian build could also have the heron client in it and that would work too

Thanks heron team you guys rock!

**Comment by mjschmidt** [comment]
I am close to getting a dev container running, having issues with step 6 on the docker page

"Step 6 — Add the bazelrc configuration file for Bazel and the compile.sh script (from the docker folder) that compiles Heron"

https://twitter.github.io/heron/docs/developers/compiling/docker/

Then I can pass y'all a base image I push to container yard that you guys could use to push a dev container under heron name if you wanted. where can I find the basil stuff from step 6?

**Comment by mjschmidt** [comment]
Right now I get a Step 10/11 : ADD bazelrc /root/.bazelrc
ADD failed: stat /var/lib/docker/tmp/docker-builder033185271/bazelrc: no such file or directory

when running from the docker folder, so I assume it was moved.

**Comment by mjschmidt** [comment]
Not the way I was hoping to do this docker file but what ever, you can use this as template for providing a container in which people can do local dev work with heron 0.17.3

I don't mind maintaining it.

`FROM centos:centos7

# Dockerfile author / maintainer
MAINTAINER mjschmidt mjschmidt

# This is passed to the heron build command via the --config flag
ENV TARGET_PLATFORM centos
ENV bazelVersion 0.9.0

RUN yum -y upgrade
RUN yum -y update
RUN yum -y install \
      automake \
      curl \
      cmake \
      openssl-devel \
      file \
      gcc \
      gcc-c++ \
      git \
      kernel-devel \
      libtool \
      make \
      patch \
      python \
      python-devel \
      python-setuptools \
      zip \
      unzip \
      vim \
      wget \
      which

RUN yum -y install java-1.8.0-openjdk java-1.8.0-openjdk-devel

ENV JAVA_HOME /usr/lib/jvm/java-1.8.0


Run git clone https://github.com/twitter/heron.git
RUN curl -LO http://github.com/twitter/heron/releases/download/0.17.3/heron-install-0.17.3-centos.sh
RUN chmod +x heron-install-0.17.3-centos.sh
RUN ./heron-install-0.17.3-centos.sh


#@TODO I want to get heron completely compiled from github at some point... unfortunately dockering inside of docker is hard and the container wants to do docker things
#RUN heron-install-0.17.3-centos.sh
#RUN heron/docker/scripts/build-artifacts.sh centos7 0.17.3 ~/heron-release

#RUN ~/heron-release/heron-install-0.17.3-centos7.sh


#ADD bazelrc /root/.bazelrc
#ADD scripts/compile-platform.sh /compile-platform.sh
`

**Comment by kramasamy** [comment]
Michael - If this is for dev with all the dependencies - we have one already.  Checkout the containers

streamlio/build-centos7
streamlio/build-ubuntu14.04
streamlio/build-centos6

Please try it out and let us know.

**Comment by mjschmidt** [comment]
orchapod/herondev could be used for heron as of 0.17.3 let me know if you'd like me to tag according to heron version installed, and how I should handle other changes that might need container changes. (0.17.3.x? based on version of container I am running?)

**Comment by mjschmidt** [comment]
@kramasamy I think this is solved for the 17.4 or 17.5 release right?

This can also be found at orchapod/herondev

**Comment by kramasamy** [comment]
It will be solved in 0.17.5

**Comment by mjschmidt** [comment]
I think this is solved now? I checked the container and it looks good.

**Comment by kramasamy** [comment]
Yes - this is solved!

**Comment by mjschmidt** [comment]
This can be closed as resuloved :)
