### ISSUE TITLE
Heron submission works incorrectly with kubernetes with special characters

### ISSUE THREAD

**Issue by aahmed-se** [apache/incubator-heron#2743]
Heron client give appropriate error message when topology name same has special character like "_"
when submitting to a kubernetes cluster , but it submits it anyways.

**Comment by Code0x58** [comment]
I recall getting an exception message when trying to submit a topology to kubernetes which didn't follow it's naming constraints (alphanum+-_ in up to 64 characters), so I think this is ok now

**Comment by nicknezis** [comment]
Correct, I believe there is now name validation in the Kubernetes scheduler. Closing the issue.
