### ISSUE TITLE
Metrics for G1 garbage collector need to be parsed correctly

### ISSUE THREAD

**Issue by kramasamy** [apache/incubator-heron#2757]

**Comment by maosongfu** [comment]
Currently, heron-instance does gather the metrics `gc-count` and `gc-time-ms` for all types of gc in JVMMetrics (https://github.com/twitter/heron/blob/a905adde3888f508dfd6c9b57e1959f093810674/heron/common/src/java/com/twitter/heron/common/utils/metrics/JVMMetrics.java#L411).

And the metric name is: __jvm-gc-count/{GarbageCollectorMXBeanName}.
For instance, for G1GC:
`__jvm-gc-time-ms/G1-Old-Generation`
`__jvm-gc-count/G1-Old-Generation`
`__jvm-gc-time-ms/G1-Young-Generation`
`__jvm-gc-count/G1-Young-Generation`
Notice, these metrics are accumulative values so you would have to do a `rate` if you want to know the gc behavior for every particular interval.

Also, we have gc metrics summing up all types of gc for a jvm process:
`__jvm-gc-collection-time-ms`
`__jvm-gc-collection-count`

Attached an example generated by the file-sink in metrics-mgr: 
[metrics.txt](https://github.com/twitter/heron/files/1777358/metrics.txt)
`localhost:1/exclaim1/container_1_exclaim1_1` is using G1GC by adding `"-XX:-UseConcMarkSweepGC -XX:+UseG1GC -XX:MaxGCPauseMillis=200"` to `Config.TOPOLOGY_WORKER_CHILDOPTS`

**Comment by sreev** [comment]
"-XX:+UseConcMarkSweepGC" is removed in JDK 9, a humble FYI!

**Comment by nicknezis** [comment]
I believe this issue has been resolved. Closing it for now. Please add a new issue if there is still an issue.
