### ISSUE TITLE
Homebrew directions are incorrect

### ISSUE THREAD

**Issue by jcoyne** [apache/incubator-heron#2795]
On this page https://twitter.github.io/heron/docs/getting-started/#macos-homebrew

it indicates a user should:

```
$ brew install heron
```

However homebrew has no such package.  

On the mailing list it was suggested to use:

```
$ brew tap streamlio/homebrew-formulae
```

but even that results in errors.  See https://github.com/streamlio/homebrew-formulae/issues/2

I would suggest updating the webpage to completely remove the homebrew directions until these issues are resolved.

**Comment by kramasamy** [comment]
@jcoyne - we are working on correcting this issue for the upcoming release 0.17.8. Will keep you posted.

**Comment by aahmed-se** [comment]
the homebrew-formulae is fixed please run brew update.

**Comment by SioKCronin** [comment]
The error I get when I follow these instructions is: Error: `No available formula with the name "heron"`

**Comment by aahmed-se** [comment]
Hi @SioKCronin 
I tried the steps below on a fresh brew install and it works fine.

```
brew tap streamlio/homebrew-formulae
brew update
brew install heron
```
