### ISSUE TITLE
YAML cpp noboost deprecated

### ISSUE THREAD

**Issue by comes5** [apache/incubator-heron#2890]
After cloning the repository: `git clone --branch 0.17.8 https://github.com/apache/incubator-heron.git`
I started building with Bazel, but there was an error:
`ERROR: /media/sf_VBoxFolder/incubator-heron/heron/instance/src/cpp/BUILD:3:1: no such package '@com_github_jbeder_yaml_cpp//': Error downloading [https://storage.googleapis.com/heron-packages/yaml-cpp-noboost.tar.gz] to /home/alberto/.cache/bazel/_bazel_alberto/55d63e2b32405818ff4fc73c3f078816/external/com_github_jbeder_yaml_cpp/yaml-cpp-noboost.tar.gz: GET returned 400 Bad Request and referenced by '//heron/instance/src/cpp:heron-cpp-instance'
ERROR: Analysis of target '//heron/instance/src/cpp:heron-cpp-instance' failed; build aborted: no such package '@com_github_jbeder_yaml_cpp//': Error downloading [https://storage.googleapis.com/heron-packages/yaml-cpp-noboost.tar.gz] to /home/alberto/.cache/bazel/_bazel_alberto/55d63e2b32405818ff4fc73c3f078816/external/com_github_jbeder_yaml_cpp/yaml-cpp-noboost.tar.gz: GET returned 400 Bad Request
INFO: Elapsed time: 4.749s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (1 packages loaded)
`
It seems that yaml-cpp-noboost.tar.gz can't be downloaded from googleapi storage.
Maybe it's deprecated because with YAML 0.6.0 the dependency with Boost is gone [https://github.com/jbeder/yaml-cpp/releases/tag/yaml-cpp-0.6.0](url)

**Comment by nwangtw** [comment]
Related PR:
https://github.com/apache/incubator-heron/pull/2893/files
