### ISSUE TITLE
Cannot find the scheduler logs of Heron cluster using aurora-scheduler

### ISSUE THREAD

**Issue by Yitian-Zhang** [apache/incubator-heron#2944]
When I deployed heron cluster using aurora-scheduler and mesos, I can't find the scheduler logs of heron anywhere. Unlike heron deployed on local environment, I can find the scheduler logs file in the log-files folder, but I can't find the file in the heron cluster using aurora-scheduler.

**Comment by kramasamy** [comment]
@Yitian-Zhang - the logs will be local during the submission process. You can see the logs using 

```
heron submit <cluster> --verbose
```
Hope this helps.

**Comment by Yitian-Zhang** [comment]
Thanks for your help, and  I have already used `--verbose` parameter for displaying the output. So it means I can only get the scheduler log by using the parameter, and I can't get a `scheduler log file` just like running on `local mode`, is it right?

**Comment by kramasamy** [comment]
heron --verbose gives the logs until the submission of the job is done - either success or failure. After that the logs of scheduler will give some idea about what happened. Once the scheduler schedules the job - tmaster, stmgr, instances log are available.

**Comment by Yitian-Zhang** [comment]
Thanks a lot.
