### ISSUE TITLE
When deployed on Minikube, some buttons on Heron UI does not work properly

### ISSUE THREAD

**Issue by simingweng** [apache/incubator-heron#3021]
Steps to reproduce:

1. deploy Heron on Minikube
2. submit an example topology and make sure all its pods are in running state
3. "kubectl proxy"
4. open the Heron UI in browser via the proxied URL
5. select either a spout or bolt instance in the physical plan diagram
6. the three buttons, "log", "job", "exception" right beneath the instance metrics chart does not work because the URL it points to has one part missing in it. For example, the "log" button has a URL of `http://localhost:8001/topologies/kubernetes/default/simon-word-count/1/file?path=./log-files/container_1_word_1.log.0`, but it is supposed to be `http://localhost:8001/api/v1/namespaces/default/services/heron-ui:8889/proxy/topologies/kubernetes/default/simon-word-count/1/file?path=./log-files/container_1_word_1.log.0`

the misbehaving buttons are highlighted in the screenshot below
![screen shot 2018-09-07 at 9 45 48 pm](https://user-images.githubusercontent.com/4026795/45257977-4550b080-b37d-11e8-87fc-d8384dd9f8ab.png)

when clicking on the "log" button, a wrong page appears as below
![screen shot 2018-09-07 at 9 47 52 pm](https://user-images.githubusercontent.com/4026795/45257986-77621280-b37d-11e8-8bf6-5104889161f4.png)

**Comment by worlvlhole** [comment]
Same issue here using heron helm chart deploying in GKE.

**Comment by nicknezis** [comment]
This has been resolved.
