### ISSUE TITLE
Java 9 support: Add support for JVM unified logging flags

### ISSUE THREAD

**Issue by rohanag12** [apache/incubator-heron#3268]
The heron executor has some hard coded flags to enable GC logging. The flag format has changed to the unified logging format https://openjdk.java.net/jeps/158 starting in Java 9, and this change is not backwards compatible.

Heron executor should pick up the right format based on Java version.

**Comment by nicknezis** [comment]
Heron now supports JDK 11 and should be using the unified logging format introduced in JDK 9. If you find that something is still missing, please open a new ticket. Thank you!
