### ISSUE TITLE
Some components do not properly override config

### ISSUE THREAD

**Issue by rohanag12** [apache/incubator-heron#3287]
The Heron executor reads statemgr locations from the `statemgr.yaml` config file, but it does not read overrides from `override.yaml`. This causes it to connect to the wrong statemgr if a topology relies on the override config file.

The same applies to metrics manager. It picks out certain config from the override config, but ignores some important ones (like the list of metrics sinks to use).

Is this by design? If so, what is the reasoning behind it?
If not, can I submit a patch to make these components properly override config by reading from `override.yaml`?

**Comment by nwangtw** [comment]
I think it is likely to be an in-completed feature and good to move forward.

@huijunw @nlu90 you can confirm?

**Comment by huijunwu** [comment]
all components should work in the same way - read the default config yaml, then override the config with `override.yaml`

**Comment by rohanag12** [comment]
Makes sense, thanks! I'll send out patches for some of the components I found that do not override the config.

**Comment by nlu90** [comment]
Here is how the override config operation is done: [Config Override](https://github.com/apache/incubator-heron/blob/5ee2490c025c7684c097962cf6d25f54ead73cf4/heron/spi/src/java/org/apache/heron/spi/common/ConfigLoader.java#L61). By design, all the default configs will be overridden by the override config.

Could you be more specific which configs are not overridden correctly?

**Comment by rohanag12** [comment]
@nlu90 The `loadConfig` function you linked looks ideal. However, it is not used in all Java code.

Take a look at https://github.com/apache/incubator-heron/compare/master...uhanaio:executor-overload-config for an example. In metrics manager, the list of metrics sinks to load is read separately, in the [MetricsSinksConfig](https://github.com/uhanaio/incubator-heron/blob/master/heron/metricsmgr/src/java/org/apache/heron/metricsmgr/MetricsSinksConfig.java) class.

Also part of that diff is a change to heron executor, where it does not override the statemgr config from `overrides.yaml`.

**Comment by rohanag12** [comment]
Resolved by #3292 and #3293
