### ISSUE TITLE
Critical Zookeeper Vulnerability

### ISSUE THREAD

**Issue by the-scott-hand** [apache/incubator-heron#3338]
Zookeeper has a critical vulnerability in versions prior to 3.4.14: [https://zookeeper.apache.org/security.html](https://zookeeper.apache.org/security.html)
I am using the helm chart, which only supports choosing the same image for both heron-tools and heron-zookeeper stateful sets. heron/heron:0.17.8 included zookeeper 3.4.10

Are there any heron images availible that do not include use a zookeeper with this vulnerability? Aka one using at least zookeeper 3.4.14 

What is the latest version of zookeeper heron has been tested with?

**Comment by the-scott-hand** [comment]
any word on this?

**Comment by nwangtw** [comment]
Thanks for bringing it up. This should be fixed asap.

Any recommendation which version we should use?

**Comment by nwangtw** [comment]
Also please feel free to make the code change (hopefully the WORKSPACE file only?) if you would like to.

Thanks in advance!

**Comment by the-scott-hand** [comment]
Confluent zookeeper([https://github.com/confluentinc/cp-helm-charts/tree/master/charts/cp-zookeeper](https://github.com/confluentinc/cp-helm-charts/tree/master/charts/cp-zookeeper)) is using zookeeper-3.4.14 in their 5.3.0 release, which i believe is the earliest version without the issue. Has any version of heron been tested with at least this version of zookeeper?

**Comment by nwangtw** [comment]
Currently ZK release is release-3.5.5, and 3.4.14 was relelased on Apr 1 and it isn't too old. 

I think it makes sense to upgrade to this version.

**Comment by joshfischer1108** [comment]
You should be able to point your configs to an external zookeeper instance and just ignore the embedded zookeeper running the 0.17.8 containers

**Comment by nwangtw** [comment]
Created a PR: https://github.com/apache/incubator-heron/pull/3339. Please let me know if there is any concern.

**Comment by nwangtw** [comment]
Code merged into master~

Thanks again for the information! @the-scott-hand

**Comment by the-scott-hand** [comment]
@joshfischer1108 the helm chart as it sits in the repo forces the use of the same image for heron tools as it does for zookeeper:  https://github.com/apache/incubator-heron/blob/dd6da67da7972791639746dd9190fd919ba6986c/deploy/kubernetes/helm/templates/zookeeper.yaml#L83 

I can work around that, but I did want to bring that to your attention as another potential issue.

What is the latest version of zookeeper that has been tested with heron? I’m concerned about using an untested zookeeper heron combo in my environment. Am I being overly cautious? What tests have you guys run(if any) to verify this version of zookeeper doesn’t break anything?

**Comment by the-scott-hand** [comment]
Also thank you very much for being responsive to this ticket and making the update so quickly!!

**Comment by nwangtw** [comment]
> @joshfischer1108 the helm chart as it sits in the repo forces the use of the same image for heron tools as it does for zookeeper:
> 
> https://github.com/apache/incubator-heron/blob/dd6da67da7972791639746dd9190fd919ba6986c/deploy/kubernetes/helm/templates/zookeeper.yaml#L83
> 
> I can work around that, but I did want to bring that to your attention as another potential issue.
> 
> What is the latest version of zookeeper that has been tested with heron? I’m concerned about using an untested zookeeper heron combo in my environment. Am I being overly cautious? What tests have you guys run(if any) to verify this version of zookeeper doesn’t break anything?

Sure thing. This is an easy/quick change at least.

It is definitely not overly cautious. :)  I have the same concern when making the change. Integration tests don't rely on zk so it is not covered.

For us the zookeeper cluster is maintained by a different team and there could be internal changes, so I have no idea which version it is. :D  But I feel it is a reasonable expectation for them to be compatible.  This zk release has been a few month till now and it has been used by other project. So I am feeling relatively comfortable. Anyways, more testing is definitely a good idea.

**Comment by the-scott-hand** [comment]
thanks again for the help, would you mind updating this ticket when further testing has been done? I'm looking for something to point to in order to make the case that we should update our environment to use this version other than "works for my stuff"

**Comment by nwangtw** [comment]
Will do.

**Comment by nwangtw** [comment]
The new version seems to be working fine with our test topology.

**Comment by the-scott-hand** [comment]
Awesome. Thanks again for the help!

**Comment by nicknezis** [comment]
If Zookeeper 5.3.0 is the earliest version without the critical bug, then the Docker distribution build scripts should be updated from 3.4.10. The accepted merge request only updated the client library. 
Somewhat relates to this issue. #3408

**Comment by the-scott-hand** [comment]
@nicknezis for this particular issue I believe the earliest without the bug was zookeeper 3.4.14(which was the version used by confluent in their 5.3.0 release), but i agree I don’t see any reason why the Dockerfiles should still be pointing to 3.4.10

**Comment by nwangtw** [comment]
You are right. I updated only the zk client version since it is the code linked to the binary. It is better for all components to be consistent. Let me see what we need to do.
