### ISSUE TITLE
Need the stream-manager(stmgr) memory usage metrics.

### ISSUE THREAD

**Issue by thinker0** [apache/incubator-heron#3396]
#1908 

Container oom-killer 
![image](https://user-images.githubusercontent.com/357785/68469970-8634a580-025e-11ea-9780-fb5579f8fcbb.png)

-

**Comment by nwangtw** [comment]
stmgr is C++ code. We may need a memory management library that can return the total used ram.

**Comment by nicknezis** [comment]
Could something like this be useful?
https://stackoverflow.com/questions/63166/how-to-determine-cpu-and-memory-consumption-from-inside-a-process
