### ISSUE TITLE
Update documentation to Helm 3.0

### ISSUE THREAD

**Issue by nicknezis** [apache/incubator-heron#3402]
The Helm chart and install documentation should be updated for Helm 3.x. For instance the `helm init` command is no longer needed.

**Comment by joshfischer1108** [comment]
@nicknezis If you have some time it would be great if you could help update the docs.  All of the website files are now located in the `website2` directory.  There is a README that should help with building and serving the site locally for development.

**Comment by nicknezis** [comment]
@joshfischer1108 Hopefully this effort is completed with #3430 .
