### ISSUE TITLE
Update Kubernetes APIs for 1.16

### ISSUE THREAD

**Issue by nicknezis** [apache/incubator-heron#3403]
Various Kubernetes APIs were deprecated in 1.16. The various Heron Kubernetes yamls (and maybe code?) need to be updated to use the newer APIs. Kubernetes documentation on the changes can be found here: https://kubernetes.io/blog/2019/07/18/api-deprecations-in-1-16/

Example line that needs to be updated: https://github.com/apache/incubator-heron/blob/d8db1c50b499c823e319fd16a4476a02f525a367/deploy/kubernetes/helm/templates/tools.yaml#L31

**Comment by joshfischer1108** [comment]
@nicknezis any chance you could open up a PR to address these issues?

**Comment by nicknezis** [comment]
I've started the work. Also updating code to solve #3259

**Comment by nicknezis** [comment]
I bumped the API up from 1.0.0-beta3 to 3.0.0. I'm currently working on and testing a fix to use the latest 6.0.1. But this has more API changes so will take slightly longer.

**Comment by nicknezis** [comment]
This was completed by #3426
