### ISSUE TITLE
Update Kubernetes proxy URLs

### ISSUE THREAD

**Issue by ShawnZhong** [apache/incubator-heron#3404]
This is briefly mentioned in the comment of a previous issue https://github.com/apache/incubator-heron/issues/2913#issuecomment-448798534. 

Kubernetes made an API change to the proxy URL, which brakes some links in this repository. 

Proxy URLs used to have `/proxy` in the middle, but it is moved to the end (See https://kubernetes.io/docs/tasks/access-application-cluster/access-cluster/#manually-constructing-apiserver-proxy-urls) 

The list of links that need to be changed can be found [here](https://github.com/apache/incubator-heron/search?q=%22api%2Fv1%2Fproxy%22&unscoped_q=%22api%2Fv1%2Fproxy%22)

![image](https://user-images.githubusercontent.com/6421097/69495478-0c6eff80-0e8d-11ea-998d-c6b7edb9309e.png)

[Here](https://github.com/apache/incubator-heron/search?q=%22api%2Fv1%2Fnamespaces%22&unscoped_q=%22api%2Fv1%2Fnamespaces%22) is a list of links follows to the newest API: 

![image](https://user-images.githubusercontent.com/6421097/69495515-52c45e80-0e8d-11ea-9783-2ea723414873.png)

**Comment by joshfischer1108** [comment]
Thanks for the note @ShawnZhong.  We will hopefully get it addressed soon!
