### ISSUE TITLE
Distribution Docker images don't all include Zookeeper

### ISSUE THREAD

**Issue by nicknezis** [apache/incubator-heron#3408]
Ubuntu 14 includes Zookeeper and associated support scripts. But the newer Ubuntu, Debian and Centos Dockerfiles are missing the necessary Zookeeper files.

**Comment by nwangtw** [comment]
https://github.com/apache/incubator-heron/pull/3411

**Comment by nwangtw** [comment]
Hopefully, it is ok now? @nicknezis

**Comment by nicknezis** [comment]
Yes, this has been fixed in #3411 and #3424 .
