### ISSUE TITLE
compile error： name 'maven_server' is not defined

### ISSUE THREAD

**Issue by dttlgotv** [apache/incubator-heron#3452]
I get the latest code and compile it on macos according to the doc.
But many errors are seen.

macdeMacBook-Pro-2:incubator-heron guoxinghua$ ./bazel_configure.py
Platform Darwin
Using C compiler          :    /usr/bin/clang (10.0.1)
Using C++ compiler        :    /usr/bin/clang++ (10.0.1)
Using C preprocessor      :    /usr/bin/cpp (10.0.1)
Using C++ preprocessor    :    /usr/bin/cpp (10.0.1)
Using linker              :    /usr/bin/ld
Using JDK                 :    /Library/Java/JavaVirtualMachines/jdk1.8.0_211.jdk/Contents/Home
Using Automake            :    /usr/local/Cellar/automake/1.16.1_1/bin/automake (1.16.1)
Using Autoconf            :    /usr/local/Cellar/autoconf/2.69/bin/autoconf (2.69)
Using Make                :    /usr/bin/make (3.81)
Using Python              :    /usr/bin/python (2.7.10)
Using Libtool             :    /usr/local/Cellar/libtool/2.4.6_1/bin/glibtool (2.4.6)
Using archiver            :    /usr/bin/ar
Using coverage tool       :    /usr/bin/gcov
dwp                       :    not found, but ok
Using nm                  :    /usr/bin/nm
objcopy                   :    not found, but ok
Using objdump             :    /usr/bin/objdump
Using strip               :    /usr/bin/strip
macdeMacBook-Pro-2:incubator-heron guoxinghua$ bazel build --config=darwin heron/...
Starting local Bazel server and connecting to it...
ERROR: /Users/jj/heron/incubator-heron/WORKSPACE:38:1: name 'maven_server' is not defined

**Comment by joshfischer1108** [comment]
@dttlgotv   It looks like your are using a newer version of Bazel (prob 2.x).  You need Bazel version `0.26.0` to build Heron at this time.  You can see instructions on how to get this version [here](https://docs.bazel.build/versions/0.26.0/install.html).  

Some work is being done now to upgrade the build rules so that we can use an updated version of Bazel.

**Comment by joshfischer1108** [comment]
I just checked the documentation.. You are correct.  It is wrong.  We will work to update documentation soon.

**Comment by nicknezis** [comment]
In the meantime, you can also use Docker to compile.
`./docker/scripts/dev-env-create.sh name ubuntu14.04` (`name` is just a name for the container)
Then in the running container, you can run:
`./bazel_configure.py` and the `bazel build` commands.

**Comment by nicknezis** [comment]
There is also an ongoing effort to update the code base to support Bazel 2.X, but it is still a work in progress. 
https://github.com/apache/incubator-heron/pull/3438

**Comment by dttlgotv** [comment]
> @dttlgotv It looks like your are using a newer version of Bazel (prob 2.x). You need Bazel version `0.26.0` to build Heron at this time. You can see instructions on how to get this version [here](https://docs.bazel.build/versions/0.26.0/install.html).
> 
> Some work is being done now to upgrade the build rules so that we can use an updated version of Bazel.

thanks a lot.

**Comment by HenrietteRoeger** [comment]
Did changing Bazel help for you? I downgraded to Bazel 0.26.0, now I get the issue 

`no such attribute 'netrc' in 'http_file' rule due to the old Bazel version.

**Comment by joshfischer1108** [comment]
@HenrietteRoeger Try Bazel version 3.0.0.  This is the currently supported version.

**Comment by dttlgotv** [comment]
I got the newest codes and used 0.26 bazel，then it work.



发自我的iPhone


------------------ Original ------------------

**Comment by nicknezis** [comment]
@HenrietteRoeger Sorry for any confusion. The version of Bazel might differ depending on which branch you are using. But the latest on the `master` branch is now using 3.0.0. 

@dttlgotv What branch are you building? If it's a feature branch, then it might still be 0.26.0, but if you are building off of the master branch, it should be 3.0.0. I only mention it so you can verify that your `git pull` worked to get the latest code.

**Comment by dttlgotv** [comment]
one month ago



发自我的iPhone


------------------ Original ------------------
