### ISSUE TITLE
How can I produce jar using heron example streamlet code?

### ISSUE THREAD

**Issue by dttlgotv** [apache/incubator-heron#3455]
I want to produce jar using heroe streamlet example code in macos without compile all heron project. But I can non find any doc to introduce it.

please give me a hint.

**Comment by joshfischer1108** [comment]
You can build the streamlet example code by executing the following:
```
$ bazel build --config=darwn/ubuntu/centos/debian examples/src/java:heron-streamlet-examples
```
However, instead of having `darwn/ubuntu/centos/debian` as the config parameter value you need to select one OS value.

MacOs would be `--config=darwin`
Debian would be `--config=debian`
Ubuntu would be `--config=ubuntu`
Centos would be `--config=centos`

Hope this helps.

**Comment by nwangtw** [comment]
it is like normal java project. You just need to link heron libraries in your project to your source code.

**Comment by dttlgotv** [comment]
> You can build the streamlet example code by executing the following:
> 
> ```
> $ bazel build --config=darwn/ubuntu/centos/debian examples/src/java:heron-streamlet-examples
> ```
> 
> However, instead of having `darwn/ubuntu/centos/debian` as the config parameter value you need to select one OS value.
> 
> MacOs would be `--config=darwin`
> Debian would be `--config=debian`
> Ubuntu would be `--config=ubuntu`
> Centos would be `--config=centos`
> 
> Hope this helps.

Same issue like #3456 after I excute this command.

**Comment by dttlgotv** [comment]
> it is like normal java project. You just need to link heron libraries in your project to your source code.

Can any detail be provided?  I want to open streamlets examples in Intelli as a maven project, but it is difficult to me because many reference in heron project.

**Comment by joshfischer1108** [comment]
@dttlgotv I've added a PR #3458 that adds the examples folder to the java classpath so they are easier to work with and understand.  The best way to view the examples will be to rerun the setup intellij scripts after this PR is merged.

**Comment by joshfischer1108** [comment]
@dttlgotv #3458 has been merged into master.  Can we close this issue?

**Comment by dttlgotv** [comment]
close this issue and try it on master
