### ISSUE TITLE
compile error: Failed to fetch Maven dependency:

### ISSUE THREAD

**Issue by dttlgotv** [apache/incubator-heron#3456]
I used the neweset codes and see error below. 

ERROR: /Users/jj/heron/incubator-heron/tools/java/src/org/apache/bazel/checkstyle/BUILD:12:1: no such package '@com_google_guava_guava//jar': Failed to fetch Maven dependency: Could not transfer artifact com.google.guava:guava:jar:18.0 from/to com_google_guava_guava (http://central.maven.org/maven2/): central.maven.org and referenced by '//tools/java/src/org/apache/bazel/checkstyle:checkstyle_java'
ERROR: Analysis of target '//heron/config/src/yaml:conf-local-heron-internals' failed; build aborted: no such package '@com_google_guava_guava//jar': Failed to fetch Maven dependency: Could not transfer artifact com.google.guava:guava:jar:18.0 from/to com_google_guava_guava (http://central.maven.org/maven2/): central.maven.org
INFO: Elapsed time: 30.117s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded, 0 targets configured)

**Comment by thinker0** [comment]
In most cases, this is the latest version of bazel.

Get bazel-0.26.0 and try it out.
`` `
wget https://github.com/bazelbuild/bazel/releases/download/0.26.0/bazel-0.26.0-installer-darwin-x86_64.sh && sh bazel-0.26.0-installer-darwin-x86_64.sh --user
`` `

**Comment by dttlgotv** [comment]
I used this version truely.





发自我的iPhone


------------------ Original ------------------

**Comment by thinker0** [comment]
In my case, it happens when the master version is not. I solved it by rebase with master branch.

**Comment by joshfischer1108** [comment]
@dttlgotv This looks like a network error.  I would try to build again.

**Comment by dttlgotv** [comment]
> In my case, it happens when the master version is not. I solved it by rebase with master branch.

Same issue after I do below.

I have check tag to 0.20.1-incubating. And make sure that my bazel version is  below:

Build label: 0.26.0
Build target: bazel-out/darwin-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Tue May 28 08:38:24 2019 (1559032704)
Build timestamp: 1559032704
Build timestamp as int: 1559032704

**Comment by dttlgotv** [comment]
> @dttlgotv This looks like a network error. I would try to build again.

I changed maven url mirror, and many errors can not been seen. But some errors are left like below, please tell me where can modify the fetch url which seem I have changed.

ERROR: An error occurred during the fetch of repository 'io_bazel_rules_scala_scala_library':
   java.io.IOException: Error downloading [http://central.maven.org/maven2/org/scala-lang/scala-library/2.12.8/scala-library-2.12.8.jar] to /private/var/tmp/_bazel_guoxinghua/272388fad3c2810d9ff9b28da122efba/external/io_bazel_rules_scala_scala_library/scala-library-2.12.8.jar: Unknown host: central.maven.org

**Comment by joshfischer1108** [comment]
Could it be that you are using http and not https?

**Comment by dttlgotv** [comment]
> Could it be that you are using http and not https?

I can not connect http://central.maven.org/maven2, so I have to modify the maven repository to mirror. And the mirror is https://mirrors.****.maven/.

After this modify, many issues are not seen, but some are left yet. It is odd that why downing from http://central.maven.org/maven2/ can be seen yet like below:
ERROR: An error occurred during the fetch of repository 'io_bazel_rules_scala_scala_library':
java.io.IOException: Error downloading [http://central.maven.org/maven2/org/scala-lang/scala-library/2.12.8/scala-library-2.12.8.jar] to

I think there is another place need modify maven repository, but I can not find it.

**Comment by joshfischer1108** [comment]
You shouldn't have to change any the maven central urls.  My first thought is that there are some networking issues that are affecting the build.

**Comment by dttlgotv** [comment]
> You shouldn't have to change any the maven central urls. My first thought is that there are some networking issues that are affecting the build.

The maven url in workspace can not be connected truly in china.

**Comment by nicknezis** [comment]
There was an issue which was fixed already in which HTTP was being used instead of HTTPS. Maven Central switched to only work with HTTPS. You can read more about it here: https://blog.sonatype.com/central-repository-moving-to-https 

Make sure you are using a branch which includes this fix. https://github.com/apache/incubator-heron/pull/3436

**Comment by dttlgotv** [comment]
> There was an issue which was fixed already in which HTTP was being used instead of HTTPS. Maven Central switched to only work with HTTPS. You can read more about it here: https://blog.sonatype.com/central-repository-moving-to-https
> 
> Make sure you are using a branch which includes this fix. #3436

I checkout branch to master pulled 5 days before. The errors is below:

no such package '@commons_cli_commons_cli//jar': Failed to fetch Maven dependency: Could not transfer artifact commons-cli:commons-cli:jar:1.3.1 from/to commons_cli_commons_cli (https://repo1.maven.org/maven2/): repo1.maven.org and referenced by '//tools/java/src/org/apache/bazel/checkstyle:checkstyle_cpp

**Comment by dttlgotv** [comment]
> > There was an issue which was fixed already in which HTTP was being used instead of HTTPS. Maven Central switched to only work with HTTPS. You can read more about it here: https://blog.sonatype.com/central-repository-moving-to-https
> > Make sure you are using a branch which includes this fix. #3436
> 
> I checkout branch to master pulled 5 days before. The errors is below:
> 
> no such package '@commons_cli_commons_cli//jar': Failed to fetch Maven dependency: Could not transfer artifact commons-cli:commons-cli:jar:1.3.1 from/to commons_cli_commons_cli (https://repo1.maven.org/maven2/): repo1.maven.org and referenced by '//tools/java/src/org/apache/bazel/checkstyle:checkstyle_cpp

I cancel the proxy and compile again, the error is below:

DEBUG: Rule 'io_bazel_rules_scala' indicated that a canonical reproducible form can be obtained by modifying arguments sha256 = "5abd638278de10ccccb0b4d614158f394278b828708ba990461334ecc01529a6"
ERROR: /Users/cc/heron/incubator-heron/tools/java/src/org/apache/bazel/checkstyle/BUILD:12:1: no such package '@com_puppycrawl_tools_checkstyle//jar': Failed to fetch Maven dependency: Could not transfer artifact com.puppycrawl.tools:checkstyle:jar:6.17 from/to com_puppycrawl_tools_checkstyle (https://repo1.maven.org/maven2/): repo1.maven.org and referenced by '//tools/java/src/org/apache/bazel/checkstyle:checkstyle_java'
ERROR: Analysis of target '//heron/config/src/yaml:conf-local-client' failed; build aborted: no such package '@com_puppycrawl_tools_checkstyle//jar': Failed to fetch Maven dependency: Could not transfer artifact com.puppycrawl.tools:checkstyle:jar:6.17 from/to com_puppycrawl_tools_checkstyle (https://repo1.maven.org/maven2/): repo1.maven.org
INFO: Elapsed time: 30.216s
INFO: 0 processes.
FAILED: Build did

**Comment by nicknezis** [comment]
Is it maybe timing out when downloading the artifact? Do you get the same error when running multiple times?

**Comment by dttlgotv** [comment]
> Is it maybe timing out when downloading the artifact? Do you get the same error when running multiple times?

different errors. I compile again , the error is :

ERROR: An error occurred during the fetch of repository 'org_apache_zookeeper':
   java.io.IOException: Error downloading [https://archive.apache.org/dist/zookeeper/zookeeper-3.4.14/zookeeper-3.4.14.tar.gz] to /private/var/tmp/_bazel_guoxinghua/272388fad3c2810d9ff9b28da122efba/external/org_apache_zookeeper/zookeeper-3.4.14.tar.gz: connect timed out

**Comment by nicknezis** [comment]
This is a good sign because you are making progress. It seems it is related to your internet connection and not the logic in the build. You can keep trying until you have all of the dependencies downloaded locally. Bazel will cache the downloaded files so future builds should work better. You can also run a http cache if this helps. Something like Squid proxy could maybe help. Here is an example. https://wiki.squid-cache.org/ConfigExamples/Caching/CachingAVUpdates

I'm closing this issue for now unless you have a new finding.
