### ISSUE TITLE
An error occurred during the fetch of repository 'org_apache_zookeeper'

### ISSUE THREAD

**Issue by dttlgotv** [apache/incubator-heron#3460]
error:
 java.io.IOException: Error downloading [https://archive.apache.org/dist/zookeeper/zookeeper-3.4.14/zookeeper-3.4.14.tar.gz] to /private/var/tmp/_bazel_zz/272388fad3c2810d9ff9b28da122efba/external/org_apache_zookeeper/zookeeper-3.4.14.tar.gz: connect timed out

It seems downloading is well except it is very slow. So I try to download it manually.
And I can manually download  zookeeper-3.4.14.tar.gz from https://archive.apache.org/dist/zookeeper/zookeeper-3.4.14/zookeeper-3.4.14.tar.gz well though it is slow.

How can I let heron use my downloaded zookeeper and ignore downloading again?

**Comment by nicknezis** [comment]
Once Bazel downloads the artifact it should re-use it. If you can't get this to work, you can try running a http cache and use `--remote_http_cache` flag. I've never used this before so maybe do a little bit of research. https://cacm.acm.org/magazines/2019/1/233524-using-remote-cache-service-for-bazel/fulltext

**Comment by dttlgotv** [comment]
big help, thanks a lot.
