### ISSUE TITLE
How can I install the newest release version?

### ISSUE THREAD

**Issue by dttlgotv** [apache/incubator-heron#3468]
I only install 0.17.8 version using "brew install herom". And I fail to compile the newest code.

How can I get the newest release version include the newest code function in macosx?

**Comment by nwangtw** [comment]
Yeah. We haven't publish the newer version to brew for a really long time. For pre 0.20, you can download the installer from github release page. We are trying to include installer in release currently but it is not happening yet. So compiling from source code is the only way currently. :(

**Comment by nwangtw** [comment]
Here is an instruction I am preparing for the next meetup fyi: https://docs.google.com/document/d/16fahYUptArOLq46oRqc7wMWgDLTIBdd6ijH2yiGeYJ0/edit#heading=h.ruwvkot1x6eq

**Comment by dttlgotv** [comment]
> Here is an instruction I am preparing for the next meetup fyi: https://docs.google.com/document/d/16fahYUptArOLq46oRqc7wMWgDLTIBdd6ijH2yiGeYJ0/edit#heading=h.ruwvkot1x6eq

To compile the newest code, must docker be used?  It is why I can not compile well according to the doc https://heron.incubator.apache.org/docs/getting-started-local-single-node/?

**Comment by dttlgotv** [comment]
I can compile well on the newest code.
