### ISSUE TITLE
Python 3 upgrade

### ISSUE THREAD

**Issue by nicknezis** [apache/incubator-heron#3480]
We need to upgrade our entire repo to use Python 3 instead of the current Python 2.

Some initial work was done and is captured in this branch: #3479 

Please submit pull requests to this branch as we coordinate our combined efforts to upgrade the repo.

**Comment by samialabed** [comment]
What test failed in #3478 that halted this?

I am happy to work on this but would like to know what caused the revert

**Comment by nwangtw** [comment]
I remember it is packaging related, maybe wheel?

**Comment by nicknezis** [comment]
Yes and import statements were not able to find the protobuf generated python code. Seemed like a Python 2 vs 3 path issue.

**Comment by nicknezis** [comment]
What was weird was that it passed in TravisCI, but then a few of us started having issues. I originally assumed that the issues were related to my branch in which I was upgrading Bazel, but then others started reporting issues.

I've made a new branch with the changes here: #3479 . @samialabed If it helps, feel free to submit any merge requests to that branch.

**Comment by HenrietteRoeger** [comment]
I just built the latest version with Bazel (3.1) on a MacOS 10.14.  and get the following error on any command line input (heron version, heron-tracker etc). Default Python is 3.7, but according to the stack, it properly finds python 2.7. 

> Traceback (most recent call last):
>   File ".bootstrap/_pex/pex.py", line 365, in execute
>   File ".bootstrap/_pex/pex.py", line 293, in _wrap_coverage
>   File ".bootstrap/_pex/pex.py", line 325, in _wrap_profiling
>   File ".bootstrap/_pex/pex.py", line 408, in _execute
>   File ".bootstrap/_pex/pex.py", line 466, in execute_entry
>   File ".bootstrap/_pex/pex.py", line 471, in execute_module
>   File "/usr/local/Cellar/python@2/2.7.15/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 192, in run_module
>     fname, loader, pkg_name)
>   File "/usr/local/Cellar/python@2/2.7.15/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
>     exec code in run_globals
>   File "heron/tools/cli/src/python/main.py", line 42, in <module>
>     import heron.tools.cli.src.python.submit as submit
>   File "heron/tools/cli/src/python/submit.py", line 34, in <module>
>     from heron.proto import topology_pb2
>   File "heron/proto/topology_pb2.py", line 24, in <module>
> TypeError: __init__() got an unexpected keyword argument 'serialized_options'

Does this relate to the issues the others reported?

**Comment by joshfischer1108** [comment]
@HenrietteRoeger Try Bazel version 3.0.0.  This is the currently supported version.

**Comment by huijunwu** [comment]
the master branch is on py3 now.
