### ISSUE TITLE
How is protobuf  used in heron?

### ISSUE THREAD

**Issue by dttlgotv** [apache/incubator-heron#3499]
In current code java protobuf 3.6.1 version is used.
And when I submit topo to yarn it seems that python use protobuf too which version is 3.6.1.

Anyone can tell me when a topo is submitted, how does protobuf is used?

**Comment by huijunwu** [comment]
protobuf mainly for the communication between tmaster <-> stmgr and stmgr<->instance. but it is also used in some other situations such as proto over http for tracker.
