### ISSUE TITLE
The build does not work with Java version greater than 11

### ISSUE THREAD

**Issue by NareshKosgi** [apache/incubator-heron#3516]
Currently, if you try to build using a version higher than Java 11 the build runs into the following Javadoc issue.  I know currently, there are not any plans to update but I figured I add this issue so that the team is aware when that decision is made.

**Comment by nwangtw** [comment]
cool. thx. @thinker0 created this PR: https://github.com/apache/incubator-heron/pull/3512 but it is failing tests currently. You may want to give it a try if you need.

**Comment by thinker0** [comment]
On my MacBook jdk13, it succeeds.

**Comment by nicknezis** [comment]
I believe the Javadoc issue was resolved. Closing this issue. Please let us know if the issue persists. If so we will re-open this issue.
