### ISSUE TITLE
Website is broken

### ISSUE THREAD

**Issue by HenrietteRoeger** [apache/incubator-heron#3543]
**Describe the bug**
The website (http://heron.incubator.apache.org/) has a broken layout. One cannot access any links on the documentation page. 
Further, most of the internal links are broken, too. Both to the java/py docs and within the general documentation 
**To Reproduce**
1. Go to http://heron.incubator.apache.org/
Example of broken link: The explanation of how to serialize custom tuples from the Tuple-Description page.

**Expected behavior**
A website with usable navigation. 

**Screenshots**
![Bildschirmfoto 2020-06-22 um 14 36 00](https://user-images.githubusercontent.com/25883266/85288291-c5ce9b80-b495-11ea-951d-82c11dc3332a.png)
![Bildschirmfoto 2020-06-22 um 14 36 49](https://user-images.githubusercontent.com/25883266/85288325-d3842100-b495-11ea-9ac4-a19f011f6d58.png)

**Operating System**
MacOS 10.14.6
Browser both Chrome or Safari

**Comment by joshfischer1108** [comment]
@HenrietteRoeger Thank you for the issue. Yes the website layout became all wrong a week or two ago for unknown reasons (at least that I can see).  We are working to resolve it.

**Comment by joshfischer1108** [comment]
I'll keep this issue updated when we have a fix.

**Comment by Xcess** [comment]
Disabling a css seems to fix the issue (I'm no web developer just tried it by myself)
`position: fixed;`

![image](https://user-images.githubusercontent.com/3321951/85388490-64710000-b55b-11ea-9b5b-6afe8f576c6f.png)

**Comment by nicknezis** [comment]
I think we will have this fixed in #3546. I've pushed a fix so the [website](http://heron.incubator.apache.org/) should be working now.

Let me know if you still see any issues.
