### ISSUE TITLE
Help, error zlib

### ISSUE THREAD

**Issue by nicolasaraya77** [apache/incubator-heron#3545]
hi everyone, i tried install heron in my noteook   (ubuntu 19.10) with the steps from docs folder and y have this error:  

ERROR: /home/nico/Escritorio/tarea4cripto/apacheheron/incubator-heron/heron/executor/src/python/BUILD:13:11: PexPython heron/executor/src/python/heron-executor.pex failed (Exit 1)
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/runpy.py", line 165, in _run_module_as_main
    mod_name, loader, code, fname = _get_main_module_details(_Error)
  File "/usr/local/lib/python2.7/runpy.py", line 133, in _get_main_module_details
    return _get_module_details(main_name)
  File "/usr/local/lib/python2.7/runpy.py", line 121, in _get_module_details
    raise error(format(e))
ImportError: can't decompress data; zlib not available
INFO: Elapsed time: 3.583s, Critical Path: 2.36s
INFO: 3 processes: 3 local.
FAILED: Build did NOT complete successfully

i have install zlib1g but python don't use the module. help i need make a video with heron

**Comment by huijunwu** [comment]
I tried ubuntu20.04+python3, looks good to me. Do you still see this issue?

**Comment by nicknezis** [comment]
Closing this issue. Please re-open a new issue if the problem persists.
