### ISSUE TITLE
Investigate and fix zip_safe=False in PEX

### ISSUE THREAD

**Issue by Code0x58** [apache/incubator-heron#3558]
While upgrading from python2 to python3, the generated PEXs would not work due to being unable to import from at least `pex_library` includes, related to the introduction of [PEP-420](https://www.python.org/dev/peps/pep-0420/), but for some reason wasn't working with the default `zip_safe=None`/`zip_safe=True`, so the workaround was to cause the PEXs to always be extracted to disk rather than loaded straight into memory.

**Comment by joshfischer1108** [comment]
It looks like this issue was resolved with #3522 . Closing for now.
