### ISSUE TITLE
Ambiguous Bazel version for release v0.20.1-incubating-rc1

### ISSUE THREAD

**Issue by ZanZong** [apache/incubator-heron#3604]
Hi everyone.
I'm going to build v0.20.1-incubating-rc1 from released source codes. But the [https://github.com/apache/incubator-heron/blob/0.20.1-incubating/README.md](readme) doesn't specify the particular version of Bazel.

I have tried bazel-0.20.0 and bazel-0.20.1, but I got errors below. 
```
$ bazel build --config=ubuntu scripts/packages:binpkgs
WARNING: The following rc files are no longer being read, please transfer their contents or import their path into one of the standard rc files:
/home/zongzan/incubator-heron-0.20.1-incubating-rc1/tools/bazel.rc
Starting local Bazel server and connecting to it...
INFO: Options provided by the client:
  Inherited 'common' options: --isatty=1 --terminal_columns=171
ERROR: Config value ubuntu is not defined in any .rc file
INFO: Invocation ID: 4ad3c201-b571-41f8-8ecf-0a5dfd8d7ec9
```
I thought maybe the version was wrong, can you provide a specific version?
Thanks!

**Comment by Code0x58** [comment]
Bazel 3.4.1 is what is in use at the moment, I'm surprised to see it disappeared from the README.md

**Comment by Code0x58** [comment]
sorry, looks like I was looking at the wrong revision - master is on 3.4.1, 0.20.1-rc1 is on 0.26.0

**Comment by ZanZong** [comment]
Thanks!
