### ISSUE TITLE
Heron Helm chart should not use `cluster-admin` role

### ISSUE THREAD

**Issue by nicknezis** [apache/incubator-heron#3615]
**Is your feature request related to a problem? Please describe.**
The current Helm chart uses `cluster-admin` role. There should be a custom role with specific permissions. This current configuration is a blocker for components wanting to install Heron Helm chart from within Kubernetes without themselves having `cluster-admin` role permissions.

**Describe the solution you'd like**
The Heron Helm chart should have a custom `role` with the actual permissions required.

**Comment by the-scott-hand** [comment]
Agreed, see my pull request for proposed solution.

**Comment by joshfischer1108** [comment]
Should this be address before the next release candidate?

**Comment by nicknezis** [comment]
I believe the merged PR fixes this. Closing the issue.
