### ISSUE TITLE
rename "topology master" to "topology manager"?

### ISSUE THREAD

**Issue by armadillojim** [apache/incubator-heron#3622]
Howdy!  I'm relatively new to Heron, and it seems like a wonderful product.  Thanks for all your hard work in developing it!

As a newbie I've been reading through the documentation.  One thing caught my eye: the term "topology master".  Other components don't use the same word.  For example, there are the "metrics manager", "stream manager", and "zoo keeper".

If I submitted a PR to change "master" to "manager", would that be well received?  Or would such a change not be welcome?  I searched through all the issues and PRs but didn't see anything related.  Forgive me if this conversation has already been hashed through.  Also, FWIW I'm suggesting "manager" in place of "master" to keep with a word beginning with "m"; that way the abbreviation "TM" doesn't change.  However, perhaps someone else could come up with a more appropriate suggestion.

**Comment by nicknezis** [comment]
I think it's a good idea. I'd be willing to review your merge request and test it out.

**Comment by armadillojim** [comment]
Thanks so much, @nicknezis!  I just created #3624.

I haven't done testing yet as the edits took me much longer than I originally anticipated.  However, I will try my best to do so over the next few days.  Any suggestions are welcome!
