### ISSUE TITLE
Add support for Pod Templates which are read from a ConfigMap. The ConfigMap name can be passed in as a config-property

### ISSUE THREAD

**Issue by nicknezis** [apache/incubator-heron#3707]
This feature request is to enhance the Kubernetes Scheduler to add support for Pod Templates (similar to [Spark's Kubernetes feature](https://spark.apache.org/docs/latest/running-on-kubernetes.html#pod-template))

By providing a Pod Template as a ConfigMap, the Heron Kubernetes Scheduler can retrieve the template and provide it as a base starting point for Pod definition.

**Comment by nicknezis** [comment]
This is the Spark Scala step that is used to create the Pod spec based on a ConfigMap PodTemplate.

https://github.com/apache/spark/blob/de59e01aa4853ef951da080c0d1908d53d133ebe/resource-managers/kubernetes/core/src/main/scala/org/apache/spark/deploy/k8s/features/PodTemplateConfigMapStep.scala

**Comment by surahman** [comment]
Hi @nicknezis, I have started poking around in the code base for `Heron` again and I am trying to wrap my head around what needs to happen here. Again, I do not have any experience in the codebase.

> By providing a Pod Template as a ConfigMap, the Heron Kubernetes Scheduler can retrieve the template and provide it as a base starting point for Pod definition.

This appears to be setting up the `Config` on the Scheduler:
https://github.com/apache/incubator-heron/blob/4d9a7de106d6f1f6de6a96f996735c5fc636011b/heron/schedulers/src/java/org/apache/heron/scheduler/kubernetes/KubernetesScheduler.java#L57-L83

The following code block appears to be creating the YAML config based on the required record structures:
https://github.com/apache/spark/blob/de59e01aa4853ef951da080c0d1908d53d133ebe/resource-managers/kubernetes/core/src/main/scala/org/apache/spark/deploy/k8s/features/PodTemplateConfigMapStep.scala#L39-L66

I am trying to figure out what my starting point for this should be on the `Heron` side, any ideas? What functionality is available as far as building the YAML record structures (`Config.Builder`)?

**Comment by surahman** [comment]
A quick review of the code in the `heron/schedulers/src/java/org/apache/heron/scheduler/kubernetes/` directory, I may have missed some stuff and will update once I re-review:

* `KubernetesConstants`: namespaced constants for configurations.
* `KubernetesContext`: child class of `Context` with Kubernetes specific keys used to lookup values (no "setters", only "getters") stored in the supplied `Config` object.
* `KubernetesController`: the basic interface with Kubernetes to recover info about the topology configs as well as submit/kill/restart them.
* `KubernetesLauncher`: used to init and launch the Kubernetes cluster.
* `KubernetesScheduler`: the interface to schedule jobs with the cluster, to get job info, kill, restart, resize, and update the cluster.
* `KubernetesUtils`: various logging utilities.
* `V1Controller`: child class of the `KubernetesController` which contains the actual logic to interface with the Kubernetes cluster.
* `Volumes`: utilities used to configure the clusters storage volumes.

**Comment by surahman** [comment]
Hi @nicknezis, I have a plan put together 🤔  and will start to hammer things out. I shall generate a WIP PR into the Heron repo once I have some of the more substantial components put together.
