### ISSUE TITLE
Renamed variable but not updating the js

### ISSUE THREAD

**Issue by windhamwong** [apache/incubator-heron#3801]
https://github.com/apache/incubator-heron/blob/9cfc5c4785ba0c14d26dfbbf0fe1d6b477dd38a5/heron/tools/ui/resources/static/js/physical-plan.js#L55

Looks like the code `containers[worker.stmgrId]` is invalid because the stmgr ID has been renamed to `worker.stmgr_id`.

![image](https://user-images.githubusercontent.com/677625/160147653-9667aaf9-db95-4b13-af67-9c7a0cd8048d.png)

I am using `/pull/3779` based on master, but the PR has no change to the code.

**Comment by nicknezis** [comment]
This is currently being worked in #3786 . Feel free to submit any pull requests to that branch as we resolve the issues. There were many more broken aspects when we updated the code to support the newer Python versions.

**Comment by nicknezis** [comment]
I believe this is now working with #3786 merged. Please re-open if it is still an issue.
