### ISSUE TITLE
Deprecation of the Apache Aurora Scheduler in Apache Heron

### ISSUE THREAD

**Issue by surahman** [apache/incubator-heron#3829]
It is the intention of the Apache Heron (Incubating) development team to deprecate support for Apache Aurora in a subsequent release. Apache Aurora was placed in the Attic in February of 2020 with development and support ceasing. For further information please refer to this [page](https://attic.apache.org/projects/aurora.html).

**Comment by thinker0** [comment]
We are currently using mainly apache aurora/mesos.  And although attic https://github.com/aurora-scheduler still has a lot of users

**Comment by surahman** [comment]
I have traced the path for removal in the event there is a desire to in the future.
