### ISSUE TITLE
404 not found api document 

### ISSUE THREAD

**Issue by joey-yoonsung** [apache/incubator-heron#3833]
**Describe the bug**
https://heron.apache.org/api/* not found.

**To Reproduce**
1. Go to https://heron.apache.org/api/org/apache/heron/api/tuple/Tuple.html
2. See error

**Expected behavior**
1.  Go to https://heron.apache.org/api/*.html
2. Show API document

**Screenshots**
<img width="547" alt="image" src="https://user-images.githubusercontent.com/25274752/169220416-5cfc9600-b4f2-4468-bee2-87952b7accc7.png">

**Operating System**
 - OS: [macOS]
 - Version [11.6.5]

**Additional context**

**Comment by thinker0** [comment]
?  https://heron.apache.org/api/java/org/apache/heron/api/tuple/Tuple.html
