### ISSUE TITLE
Private reporting of security vulnerability

### ISSUE THREAD

**Issue by Sim4n6** [apache/incubator-heron#3862]
Hi Incubatore-heron team,

I may have identified a security vulnerability in the latest code source. Could you please consider enabling the "[Private reporting of security vulnerability](https://docs.github.com/en/code-security/security-advisories/guidance-on-reporting-and-writing/privately-reporting-a-security-vulnerability)" feature in GitHub, so I could proceed privately?

Many thanks for considering my request.

**Comment by joshfischer1108** [comment]
That's  for your message, @Sim4n6.  Since Heron is an Apache project we need to follow the Apache process for reporting vulnerabilities.  
You can find more detail here: https://www.apache.org/security/

**Comment by Sim4n6** [comment]
In sum, I send the report to [security@apache.org](mailto:security@apache.org) ?

**Comment by joshfischer1108** [comment]
Yes, thank you.
