### ISSUE TITLE
create docker image with heron for distribution

### ISSUE THREAD

**Issue by kramasamy** [apache/incubator-heron#526]

**Comment by tysonnorris** [comment]
Hi - Is there a Dockerfile available to match the built image in docker hub? I need to use a local build, and would rather not stumble through recreating one that might already exist.
Thanks
Tyson

**Comment by lewiskan** [comment]
@tysonnorris I'll check in an updated version now that project is open sourced and Dockerfile can pull directly from public release, thanks.

**Comment by Code0x58** [comment]
I think https://github.com/apache/incubator-heron/issues/3239 blocks and supersedes this issue, so this can be closed

**Comment by joshfischer1108** [comment]
@Code0x58 I believe we have all the licenses figured out with the Debian10 container.  However there is a certificate issues (If I remember correctly) when running Debian10 Heron on Kubernetes. I think we need to figure this out next.

**Comment by nicknezis** [comment]
@joshfischer1108 The certificate issue is due to older JDK. Ubuntu 20.04 Dockerfile installs a new enough JDK, but I know this causes licensing issues. We can perhaps set things to use TLS 1.2 instead of 1.3, but this would need to be tested.

**Comment by nicknezis** [comment]
Heron now supports building Heron container releases. Closing this older issue.
