### ISSUE TITLE
Ability to write Python topologies

### ISSUE THREAD

**Issue by kramasamy** [apache/incubator-heron#574]
Users should be able to write python topologies and execute them. Here stream parse is the standard. If stream parse can be cleanly on top of Heron, it will satisfy the requirement.

**Comment by amontalenti** [comment]
Some notes on this:

- We have two projects, [pystorm](https://github.com/pystorm/pystorm) and [streamparse](https://github.com/Parsely/streamparse). The former is an implementation of basic APIs for bolts/spouts and implementation based on Storm's multi-lang protocol. The latter is the actual framework for managing "projects" with multiple topologies that are written using the `pystorm` API.

- As of our very-recent 3.0.0+ release, topologies themselves are specified using a Python Topology DSL, based on thriftpy to serialize the topology into a Thrift Topology struct. We serialize that by embedding a copy of `storm.thrift` inside `streamparse`, as shown [in this code](https://github.com/Parsely/streamparse/blob/master/streamparse/thrift.py).

- You can read some docs on [the way the Topology DSL works here](http://streamparse.readthedocs.io/en/stable/topologies.html#topology-dsl).

**Comment by kramasamy** [comment]
Now heron support python topologies. Please try it out and let me know.

**Comment by Code0x58** [comment]
This looks like it can be closed now

**Comment by joshfischer1108** [comment]
Thank you @Code0x58
